#!/usr/bin/env bash
# lib/publish.sh — `kitsync publish` — package local kit items and publish to GitHub
set -euo pipefail

# Directories publishable in a kit (.kitsync excluded — machine-specific config)
readonly KIT_PUBLISH_DIRS=(agents skills hooks rules scripts)

# ---------------------------------------------------------------------------
# _publish_show_manual — fallback when gh is unavailable or push fails
# Saves assembled kit to $PWD/<name> so the user can push manually.
# ---------------------------------------------------------------------------
_publish_show_manual() {
  local _tmp="$1" _name="$2" _branch="$3"

  local _kit_out
  if [[ ! -e "$PWD/$_name" ]]; then
    _kit_out="$PWD/$_name"
  else
    _kit_out="$PWD/$_name-$(date '+%Y%m%dT%H%M%S')"
  fi

  cp -R "$_tmp/." "$_kit_out"

  printf "\n" >&2
  log_info "Kit saved to: $_kit_out"
  log_info "To publish manually:"
  printf '\n    1. Create a repo at https://github.com/new\n' >&2
  printf '    2. Then run:\n\n       cd %s\n       git remote add origin <your repo URL>\n       git push -u origin %s\n\n' \
    "$_kit_out" "$_branch" >&2
  printf '    3. Share the install command:\n\n       claude-kitsync install <your repo URL>\n\n' >&2
}

# ---------------------------------------------------------------------------
# _publish_readme <name> <description> <owner> <items...>
# ---------------------------------------------------------------------------
_publish_readme() {
  local _name="$1" _desc="$2" _owner="$3"
  shift 3
  local _item

  printf '# %s\n\n%s\n\n' "$_name" "$_desc"
  printf 'A [Claude Code](https://claude.ai/code) kit installable with [claude-kitsync](https://github.com/charliinew/claude-kitsync).\n\n'
  printf '## Install\n\n```bash\nclaude-kitsync install https://github.com/%s/%s\n```\n\n' "${_owner:-YOU}" "$_name"
  printf 'Paths are stored as `__CLAUDE_HOME__` / `__HOME__`; `claude-kitsync install` points them at your machine.\n\n'
  printf '## Contents\n\n'
  for _item in "$@"; do
    printf '%s\n' "- \`$_item\`"
  done
  printf '\n---\n\nGenerated by `claude-kitsync publish`\n'
}

# ---------------------------------------------------------------------------
# _publish_files <category...> — the files a kit may contain: exactly what
# kitsync syncs (the allowlist minus dependencies, caches, secrets, logs and
# claude.ai account skills), committed or not yet
# ---------------------------------------------------------------------------
_publish_files() {
  git -C "$CLAUDE_HOME" ls-files --cached --others --exclude-standard -- "$@" 2>/dev/null | sort -u
}

# _publish_secret_in <file> — name of the first secret format in the file
_publish_secret_in() {
  local entry
  for entry in "${_SYNC_SECRET_PATTERNS[@]}"; do
    if grep -qE -- "${entry#*|}" "$1" 2>/dev/null; then
      printf '%s' "${entry%%|*}"
      return 0
    fi
  done
}

# _publish_is_text <file> — path-token filtered type (same list as sync)
_publish_is_text() {
  local pat
  for pat in "${KITSYNC_PATH_FILTERED_FILES[@]}"; do
    # shellcheck disable=SC2254  # pat is a glob on purpose
    case "$(basename "$1")" in $pat) return 0 ;; esac
  done
  return 1
}

# ---------------------------------------------------------------------------
# cmd_publish — interactive kit packaging and publishing workflow
# Publishing is public by nature: it needs someone at the keyboard, shows
# exactly what goes out, and asks before anything leaves the machine.
# ---------------------------------------------------------------------------
cmd_publish() {
  require_git_repo
  if ! _has_tty; then
    die "publish needs a terminal: it shows what would be published and asks first."
  fi

  printf "\n" >&2
  log_info "Publish a kit from $CLAUDE_HOME"; printf "\n" >&2

  # Step 1: categories that have publishable files
  local _avail=() _d
  for _d in "${KIT_PUBLISH_DIRS[@]}"; do
    [[ -n "$(_publish_files "$_d/")" ]] && _avail+=("$_d/")
  done
  [[ -n "$(_publish_files CLAUDE.md)" ]] && _avail+=("CLAUDE.md")

  if [[ ${#_avail[@]} -eq 0 ]]; then
    log_warn "Nothing to publish — no agents/, skills/, hooks/, rules/, scripts/, or CLAUDE.md in $CLAUDE_HOME"
    return 1
  fi

  # Step 2: pick categories (nothing preselected)
  local _raw_indices _i
  _raw_indices=$(_SELECT_MULTI_DEFAULT=0 _select_multi "Select items to include (Space to pick, Enter to confirm)" "${_avail[@]}")
  if [[ -z "$_raw_indices" ]]; then
    log_info "Nothing selected — aborting."
    return 0
  fi
  local _selected=()
  for _i in $_raw_indices; do
    _selected+=("${_avail[$((_i - 1))]}")
  done

  # Step 3: name, description, visibility (private unless chosen)
  printf "\n" >&2
  local _kit_name _desc _vis_choice _vis_flag _vis_label
  _kit_name=$(_read_tty "Kit name (GitHub repo name)" "claude-kit")
  [[ "$_kit_name" =~ ^[A-Za-z0-9._-]+$ ]] || die "Invalid repo name: $_kit_name"
  _desc=$(_read_tty "Description" "My Claude Code kit")
  _vis_choice=$(_select_menu "Visibility" \
    "Private — invite only" \
    "Public — anyone can see and install it")
  if [[ "$_vis_choice" == "2" ]]; then
    _vis_flag="--public"; _vis_label="PUBLIC"
  else
    _vis_flag="--private"; _vis_label="private"
  fi

  # Step 4: assemble — synced files only, secrets left out, paths tokenized
  local _tmp_dir _f _secret _n=0 _left=""
  _tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$_tmp_dir" 2>/dev/null || true' EXIT
  while IFS= read -r _f; do
    [[ -n "$_f" && -f "$CLAUDE_HOME/$_f" ]] || continue
    _secret="$(_publish_secret_in "$CLAUDE_HOME/$_f")"
    if [[ -n "$_secret" ]]; then
      _left+="    $_f  (looks like a secret: $_secret)"$'\n'
      continue
    fi
    mkdir -p "$(dirname "$_tmp_dir/$_f")"
    if _publish_is_text "$_f"; then
      paths_tokenize_stream < "$CLAUDE_HOME/$_f" > "$_tmp_dir/$_f"
    else
      cp -p "$CLAUDE_HOME/$_f" "$_tmp_dir/$_f"
    fi
    _n=$(( _n + 1 ))
  done < <(_publish_files "${_selected[@]}")

  if (( _n == 0 )); then
    log_warn "Nothing left to publish."
    return 1
  fi

  local _login=""
  command -v gh &>/dev/null && gh auth status &>/dev/null && _login="$(gh api user -q .login 2>/dev/null || true)"
  _publish_readme "$_kit_name" "$_desc" "$_login" "${_selected[@]}" > "$_tmp_dir/README.md"

  # Step 5: say exactly what goes out, then ask
  printf "\n" >&2
  log_info "About to publish $_n file(s) to a $_vis_label repository '${_login:+$_login/}$_kit_name':"
  (cd "$_tmp_dir" && find . -type f | sed 's|^\./|    |' | sort | head -40) >&2
  (( _n > 40 )) && printf '    … %d more\n' $(( _n - 40 )) >&2
  if [[ -n "$_left" ]]; then
    log_warn "Left out:"
    printf '%s' "$_left" >&2
  fi
  log_info "Your own paths are replaced by __CLAUDE_HOME__ / __HOME__."
  confirm "Publish?" || { log_info "Cancelled — nothing was published."; return 0; }

  # Step 6: git init + initial commit in temp dir
  git -C "$_tmp_dir" init -q
  git -C "$_tmp_dir" add -A
  git -C "$_tmp_dir" commit -q -m "Initial kit: $_kit_name"
  local _branch
  _branch="$(git -C "$_tmp_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"

  # Step 7: publish via gh, or leave it for a manual push
  if [[ -z "$_login" ]]; then
    log_warn "gh CLI missing or not authenticated (gh auth login) — cannot publish automatically."
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
    return 0
  fi

  local _err
  log_step "Creating GitHub repository: ${_login}/${_kit_name}..."
  if ! _err="$(gh repo create "$_kit_name" "$_vis_flag" --description "$_desc" 2>&1)"; then
    log_warn "Could not create the repository:"
    printf '%s\n' "$_err" | head -3 | sed 's/^/    /' >&2
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
    return 1
  fi

  git -C "$_tmp_dir" remote add origin "$(_gh_clone_url "${_login}/${_kit_name}")"
  log_step "Pushing to GitHub..."
  if ! _err="$(git -C "$_tmp_dir" push -q -u origin "$_branch" 2>&1)"; then
    log_warn "Push failed — saving the kit locally:"
    printf '%s\n' "$_err" | head -3 | sed 's/^/    /' >&2
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
    return 1
  fi

  printf "\n" >&2
  log_success "Kit published ($_vis_label): https://github.com/${_login}/${_kit_name}"
  log_info "Others can install it with: claude-kitsync install https://github.com/${_login}/${_kit_name}"
  printf "\n" >&2
}
