#!/usr/bin/env bash
# lib/publish.sh — `kitsync publish` — package local kit items and publish to GitHub
set -euo pipefail

# Directories publishable in a kit (.kitsync excluded — machine-specific config)
readonly KIT_PUBLISH_DIRS=(agents skills hooks rules scripts)

# ---------------------------------------------------------------------------
# _publish_show_manual — fallback when gh is unavailable or push fails
# Saves assembled kit to $PWD/<name> so the user can push manually.
# ---------------------------------------------------------------------------
_publish_show_manual() {
  local _tmp="$1" _name="$2" _branch="$3"

  local _kit_out
  if [[ ! -d "$PWD/$_name" ]]; then
    _kit_out="$PWD/$_name"
  else
    _kit_out="$HOME/$_name"
  fi

  cp -r "$_tmp/." "$_kit_out" 2>/dev/null || true

  printf "\n"
  log_info "Kit saved to: $_kit_out"
  log_info "To publish manually:"
  printf "\n"
  printf "    1. Create a repo at https://github.com/new\n"
  printf "    2. Then run:\n\n"
  printf "       cd %s\n" "$_kit_out"
  printf "       git remote add origin git@github.com:YOU/%s.git\n" "$_name"
  printf "       git push -u origin %s\n\n" "$_branch"
  printf "    3. Share the install command:\n\n"
  printf "       claude-kitsync install https://github.com/YOU/%s\n\n" "$_name"
}

# ---------------------------------------------------------------------------
# _publish_readme — generate a minimal README for the published kit
# ---------------------------------------------------------------------------
_publish_readme() {
  local _name="$1" _desc="$2"
  shift 2
  local _items=("$@")

  printf "# %s\n\n%s\n\n" "$_name" "$_desc"
  printf "A [Claude Code](https://claude.ai/code) kit installable with [claude-kitsync](https://github.com/charliinew/claude-kitsync).\n\n"
  printf "## Install\n\n\`\`\`bash\nclaude-kitsync install https://github.com/YOU/%s\n\`\`\`\n\n" "$_name"
  printf "## Contents\n\n"
  for _item in "${_items[@]}"; do
    printf "- \`%s\`\n" "$_item"
  done
  printf "\n---\n\nGenerated by \`claude-kitsync publish\`\n"
}

# ---------------------------------------------------------------------------
# cmd_publish — interactive kit packaging and publishing workflow
# ---------------------------------------------------------------------------
cmd_publish() {
  printf "\n"
  log_info "Publish a kit from $CLAUDE_HOME\n"

  # Step 1: discover non-empty publishable items
  local _avail=()
  for _d in "${KIT_PUBLISH_DIRS[@]}"; do
    local _dp="$CLAUDE_HOME/$_d"
    if [[ -d "$_dp" ]] && [[ -n "$(ls -A "$_dp" 2>/dev/null)" ]]; then
      _avail+=("$_d/")
    fi
  done
  [[ -f "$CLAUDE_HOME/CLAUDE.md" ]] && _avail+=("CLAUDE.md")

  if [[ ${#_avail[@]} -eq 0 ]]; then
    log_warn "Nothing to publish — no agents/, skills/, hooks/, rules/, scripts/, or CLAUDE.md in $CLAUDE_HOME"
    return 1
  fi

  # Step 2: multi-select items to include
  local _raw_indices
  _raw_indices=$(_select_multi "Select items to include" "${_avail[@]}")

  if [[ -z "$_raw_indices" ]]; then
    log_info "Nothing selected — aborting."
    return 0
  fi

  local _selected=()
  for _i in $_raw_indices; do
    _selected+=("${_avail[$((_i - 1))]}")
  done

  printf "\n"

  # Step 3: kit name and description
  local _kit_name
  _kit_name=$(_read_tty "Kit name (GitHub repo name)" "claude-kit")
  [[ -z "$_kit_name" ]] && _kit_name="claude-kit"

  local _desc
  _desc=$(_read_tty "Description" "My Claude Code kit")
  [[ -z "$_desc" ]] && _desc="My Claude Code kit"

  # Step 4: visibility
  local _vis_choice
  _vis_choice=$(_select_menu "Visibility" \
    "Public — anyone can install" \
    "Private — invite only")
  local _vis_flag
  [[ "$_vis_choice" -eq 1 ]] && _vis_flag="--public" || _vis_flag="--private"

  # Step 5: assemble kit in temp dir
  log_step "Assembling kit..."

  local _tmp_dir
  _tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$_tmp_dir" 2>/dev/null || true' EXIT

  for _item in "${_selected[@]}"; do
    local _src="$CLAUDE_HOME/$_item"
    local _dst="$_tmp_dir/$_item"
    if [[ -d "$_src" ]]; then
      cp -r "$_src" "$_dst" 2>/dev/null || true
    elif [[ -f "$_src" ]]; then
      cp "$_src" "$_dst" 2>/dev/null || true
    fi
  done

  # Auto-generate README.md
  _publish_readme "$_kit_name" "$_desc" "${_selected[@]}" > "$_tmp_dir/README.md"

  # Step 6: git init + initial commit in temp dir
  git -C "$_tmp_dir" init -q
  git -C "$_tmp_dir" add .
  git -C "$_tmp_dir" commit -q -m "Initial kit: $_kit_name"

  local _branch
  _branch="$(git -C "$_tmp_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"

  # Step 7: publish via gh or show manual instructions
  if ! command -v gh &>/dev/null; then
    log_warn "gh CLI not installed — cannot auto-publish."
    log_info "Install gh: https://cli.github.com"
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
    return 0
  fi

  if ! gh auth status &>/dev/null 2>&1; then
    log_warn "gh not authenticated — run: gh auth login"
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
    return 0
  fi

  local _login
  _login="$(gh api user -q .login 2>/dev/null || true)"

  log_step "Creating GitHub repository: ${_login}/${_kit_name}..."
  if ! gh repo create "$_kit_name" "$_vis_flag" --description "$_desc" 2>/dev/null; then
    log_warn "Could not create repo (may already exist) — attempting push anyway..."
  fi

  local _remote_url="git@github.com:${_login}/${_kit_name}.git"
  git -C "$_tmp_dir" remote add origin "$_remote_url" 2>/dev/null || true

  log_step "Pushing to GitHub..."
  local _pushed=false

  if git -C "$_tmp_dir" push -q -u origin "$_branch" 2>/dev/null; then
    _pushed=true
  else
    # Retry with HTTPS
    local _https_url="https://github.com/${_login}/${_kit_name}.git"
    git -C "$_tmp_dir" remote set-url origin "$_https_url" 2>/dev/null || true
    if git -C "$_tmp_dir" push -q -u origin "$_branch" 2>/dev/null; then
      _pushed=true
    fi
  fi

  if [[ "$_pushed" == true ]]; then
    printf "\n"
    log_success "Kit published!"
    printf "\n"
    log_info "Repository:   https://github.com/%s/%s" "$_login" "$_kit_name"
    log_info "Contents:     %s" "${_selected[*]}"
    printf "\n"
    log_info "Others can install with:"
    printf "\n    claude-kitsync install https://github.com/%s/%s\n\n" "$_login" "$_kit_name"
  else
    log_warn "Push failed — saving kit locally."
    _publish_show_manual "$_tmp_dir" "$_kit_name" "$_branch"
  fi
}
