#!/usr/bin/env bash
# templates/shell-wrapper.sh
#
# Reference copy of the claude() shell function injected into ~/.zshrc / ~/.bashrc.
# The authoritative generator is lib/wrapper.sh — do not edit this file directly.
#
# Sync behaviour is controlled by $CLAUDE_HOME/.kitsync/config (written by
# `claude-kitsync init` or `claude-kitsync settings`). No re-install needed
# after changing preferences.
#
# DO NOT source this file directly — use `claude-kitsync init` to install it.

# kitsync-start
# This block is managed by claude-kitsync — do not edit manually.
# To update: run `claude-kitsync init` again or edit ~/.zshrc after this block.
claude() {
  # Suppress job PID/Done notifications for background sync ops.
  # LOCAL_OPTIONS scopes the change to this function only (zsh restores on exit).
  [[ -n "${ZSH_VERSION:-}" ]] && setopt LOCAL_OPTIONS NO_MONITOR NO_NOTIFY 2>/dev/null || true

  local _ks_home="${CLAUDE_HOME:-$HOME/.claude}"
  local _ks_cfg="$_ks_home/.kitsync/config"

  # Load sync preferences (defaults: auto pull, end-of-session push)
  local _ks_pull="auto"
  local _ks_push="end_of_session"
  local _ks_timer="15"
  if [[ -f "$_ks_cfg" ]]; then
    local _v
    _v="$(grep '^KITSYNC_PULL_MODE=' "$_ks_cfg" 2>/dev/null | cut -d= -f2-)" && [[ -n "$_v" ]] && _ks_pull="$_v"
    _v="$(grep '^KITSYNC_PUSH_MODE=' "$_ks_cfg" 2>/dev/null | cut -d= -f2-)" && [[ -n "$_v" ]] && _ks_push="$_v"
    _v="$(grep '^KITSYNC_PUSH_TIMER=' "$_ks_cfg" 2>/dev/null | cut -d= -f2-)" && [[ -n "$_v" ]] && _ks_timer="$_v"
  fi

  local _ks_is_repo=false
  [[ -d "$_ks_home" ]] && git -C "$_ks_home" rev-parse --git-dir &>/dev/null 2>&1 && _ks_is_repo=true

  # Auto-pull on launch (background, non-blocking)
  # zsh: &! disowns atomically without printing PID; bash: & + disown
  if [[ "$_ks_is_repo" == true ]] && [[ "$_ks_pull" == "auto" ]]; then
    if [[ -n "${ZSH_VERSION:-}" ]]; then
      (timeout "${KITSYNC_TIMEOUT:-2}" git -C "$_ks_home" pull --rebase --autostash -q 2>/dev/null
       command -v claude-kitsync &>/dev/null && claude-kitsync _post-pull-hook 2>/dev/null || true) &!
    else
      (timeout "${KITSYNC_TIMEOUT:-2}" git -C "$_ks_home" pull --rebase --autostash -q 2>/dev/null
       command -v claude-kitsync &>/dev/null && claude-kitsync _post-pull-hook 2>/dev/null || true) &
      disown
    fi
  fi

  # Timer-based push: sentinel file controls loop lifetime
  local _ks_sentinel=""
  if [[ "$_ks_is_repo" == true ]] && [[ "$_ks_push" == "timer" ]]; then
    _ks_sentinel="$(mktemp /tmp/kitsync-XXXX 2>/dev/null || true)"
    if [[ -n "${ZSH_VERSION:-}" ]]; then
      (while [[ -f "$_ks_sentinel" ]]; do
         sleep "${_ks_timer}m"
         [[ -f "$_ks_sentinel" ]] || break
         command -v claude-kitsync &>/dev/null && \
           claude-kitsync push "kitsync: auto-push $(date '+%Y-%m-%d %H:%M')" 2>/dev/null || true
       done) &!
    else
      (while [[ -f "$_ks_sentinel" ]]; do
         sleep "${_ks_timer}m"
         [[ -f "$_ks_sentinel" ]] || break
         command -v claude-kitsync &>/dev/null && \
           claude-kitsync push "kitsync: auto-push $(date '+%Y-%m-%d %H:%M')" 2>/dev/null || true
       done) &
      disown
    fi
  fi

  # Run the real claude binary
  command claude "$@"
  local _ks_exit=$?

  # Stop timer loop
  [[ -n "$_ks_sentinel" ]] && rm -f "$_ks_sentinel" 2>/dev/null || true

  # End-of-session push (background, non-blocking)
  if [[ "$_ks_is_repo" == true ]] && [[ "$_ks_push" == "end_of_session" ]]; then
    if [[ -n "${ZSH_VERSION:-}" ]]; then
      (command -v claude-kitsync &>/dev/null && \
        claude-kitsync push "kitsync: auto-push $(date '+%Y-%m-%d %H:%M')" 2>/dev/null || true) &!
    else
      (command -v claude-kitsync &>/dev/null && \
        claude-kitsync push "kitsync: auto-push $(date '+%Y-%m-%d %H:%M')" 2>/dev/null || true) &
      disown
    fi
  fi

  return $_ks_exit
}
# kitsync-end
